name: Deploy to HF Spaces

on:
  push:
    branches:
      - 'hf-deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
      
      - name: Push to HF Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push https://HuggingFaceBot:$HF_TOKEN@huggingface.co/spaces/vinay-jose/notesMD hf-deploy:main
          